/* 
 * Easy Blockchain API
 *
 * <b>The Easy Blockchain API is an easy to use API to store entries within chains. Currently it stores entries using the bitcoin blockchain by means of Factom or Multichain. The latter also allows for a private blockchain. In the future other solutions will be made available</b>    The flow is generally as follows:  1. Make sure a context is available using the / POST endpoint. Normally you only need one context. This is the place where backend providers and blockchain implementations are being specified.  2. Make sure a chain has been created using the /chain POST endpoint. Normally you only need one or a handful of chains. This is a relative expensive operation.  3. Store entries on the chain from step 2. The entries will contain the content and metadata you want to store forever on the specified chain.  4. Retrieve an existing entry from the chain to verify or retrieve data      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.10
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Sphereon.SDK.Blockchain.Easy.Client;
using Sphereon.SDK.Blockchain.Easy.Model;

namespace Sphereon.SDK.Blockchain.Easy.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IContextApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a new backend
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backend">backend</param>
        /// <returns>Backend</returns>
        Backend CreateBackend (Backend backend);

        /// <summary>
        /// Create a new backend
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backend">backend</param>
        /// <returns>ApiResponse of Backend</returns>
        ApiResponse<Backend> CreateBackendWithHttpInfo (Backend backend);
        /// <summary>
        /// Create a new context
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>Context</returns>
        Context CreateContext (Context context);

        /// <summary>
        /// Create a new context
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>ApiResponse of Context</returns>
        ApiResponse<Context> CreateContextWithHttpInfo (Context context);
        /// <summary>
        /// Delete backend by id (not by ledgername)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <returns></returns>
        void DeleteBackend (string backendId);

        /// <summary>
        /// Delete backend by id (not by ledgername)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteBackendWithHttpInfo (string backendId);
        /// <summary>
        /// Find existing backend(s) by id (single result) and/or ledgername (multiple results). Optionally including public backends of others
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>List&lt;Backend&gt;</returns>
        List<Backend> FindBackends (string backendId, bool? includePublic = null);

        /// <summary>
        /// Find existing backend(s) by id (single result) and/or ledgername (multiple results). Optionally including public backends of others
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>ApiResponse of List&lt;Backend&gt;</returns>
        ApiResponse<List<Backend>> FindBackendsWithHttpInfo (string backendId, bool? includePublic = null);
        /// <summary>
        /// Get existing backend by id (not by ledgername). Optionally including public backend of others
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>Backend</returns>
        Backend GetBackend (string backendId, bool? includePublic = null);

        /// <summary>
        /// Get existing backend by id (not by ledgername). Optionally including public backend of others
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>ApiResponse of Backend</returns>
        ApiResponse<Backend> GetBackendWithHttpInfo (string backendId, bool? includePublic = null);
        /// <summary>
        /// Get an existing context
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>Context</returns>
        Context GetContext (string context);

        /// <summary>
        /// Get an existing context
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>ApiResponse of Context</returns>
        ApiResponse<Context> GetContextWithHttpInfo (string context);
        /// <summary>
        /// List existing backends.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;Backend&gt;</returns>
        List<Backend> ListBackends ();

        /// <summary>
        /// List existing backends.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;Backend&gt;</returns>
        ApiResponse<List<Backend>> ListBackendsWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create a new backend
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backend">backend</param>
        /// <returns>Task of Backend</returns>
        System.Threading.Tasks.Task<Backend> CreateBackendAsync (Backend backend);

        /// <summary>
        /// Create a new backend
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backend">backend</param>
        /// <returns>Task of ApiResponse (Backend)</returns>
        System.Threading.Tasks.Task<ApiResponse<Backend>> CreateBackendAsyncWithHttpInfo (Backend backend);
        /// <summary>
        /// Create a new context
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>Task of Context</returns>
        System.Threading.Tasks.Task<Context> CreateContextAsync (Context context);

        /// <summary>
        /// Create a new context
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>Task of ApiResponse (Context)</returns>
        System.Threading.Tasks.Task<ApiResponse<Context>> CreateContextAsyncWithHttpInfo (Context context);
        /// <summary>
        /// Delete backend by id (not by ledgername)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteBackendAsync (string backendId);

        /// <summary>
        /// Delete backend by id (not by ledgername)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteBackendAsyncWithHttpInfo (string backendId);
        /// <summary>
        /// Find existing backend(s) by id (single result) and/or ledgername (multiple results). Optionally including public backends of others
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>Task of List&lt;Backend&gt;</returns>
        System.Threading.Tasks.Task<List<Backend>> FindBackendsAsync (string backendId, bool? includePublic = null);

        /// <summary>
        /// Find existing backend(s) by id (single result) and/or ledgername (multiple results). Optionally including public backends of others
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>Task of ApiResponse (List&lt;Backend&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Backend>>> FindBackendsAsyncWithHttpInfo (string backendId, bool? includePublic = null);
        /// <summary>
        /// Get existing backend by id (not by ledgername). Optionally including public backend of others
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>Task of Backend</returns>
        System.Threading.Tasks.Task<Backend> GetBackendAsync (string backendId, bool? includePublic = null);

        /// <summary>
        /// Get existing backend by id (not by ledgername). Optionally including public backend of others
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>Task of ApiResponse (Backend)</returns>
        System.Threading.Tasks.Task<ApiResponse<Backend>> GetBackendAsyncWithHttpInfo (string backendId, bool? includePublic = null);
        /// <summary>
        /// Get an existing context
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>Task of Context</returns>
        System.Threading.Tasks.Task<Context> GetContextAsync (string context);

        /// <summary>
        /// Get an existing context
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>Task of ApiResponse (Context)</returns>
        System.Threading.Tasks.Task<ApiResponse<Context>> GetContextAsyncWithHttpInfo (string context);
        /// <summary>
        /// List existing backends.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;Backend&gt;</returns>
        System.Threading.Tasks.Task<List<Backend>> ListBackendsAsync ();

        /// <summary>
        /// List existing backends.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;Backend&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Backend>>> ListBackendsAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ContextApi : IContextApi
    {
        private Sphereon.SDK.Blockchain.Easy.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ContextApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ContextApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Sphereon.SDK.Blockchain.Easy.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContextApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ContextApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Sphereon.SDK.Blockchain.Easy.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Sphereon.SDK.Blockchain.Easy.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create a new backend 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backend">backend</param>
        /// <returns>Backend</returns>
        public Backend CreateBackend (Backend backend)
        {
             ApiResponse<Backend> localVarResponse = CreateBackendWithHttpInfo(backend);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new backend 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backend">backend</param>
        /// <returns>ApiResponse of Backend</returns>
        public ApiResponse< Backend > CreateBackendWithHttpInfo (Backend backend)
        {
            // verify the required parameter 'backend' is set
            if (backend == null)
                throw new ApiException(400, "Missing required parameter 'backend' when calling ContextApi->CreateBackend");

            var localVarPath = "/backends";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (backend != null && backend.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(backend); // http body (model) parameter
            }
            else
            {
                localVarPostBody = backend; // byte array
            }

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateBackend", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Backend>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Backend) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Backend)));
        }

        /// <summary>
        /// Create a new backend 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backend">backend</param>
        /// <returns>Task of Backend</returns>
        public async System.Threading.Tasks.Task<Backend> CreateBackendAsync (Backend backend)
        {
             ApiResponse<Backend> localVarResponse = await CreateBackendAsyncWithHttpInfo(backend);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create a new backend 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backend">backend</param>
        /// <returns>Task of ApiResponse (Backend)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Backend>> CreateBackendAsyncWithHttpInfo (Backend backend)
        {
            // verify the required parameter 'backend' is set
            if (backend == null)
                throw new ApiException(400, "Missing required parameter 'backend' when calling ContextApi->CreateBackend");

            var localVarPath = "/backends";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (backend != null && backend.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(backend); // http body (model) parameter
            }
            else
            {
                localVarPostBody = backend; // byte array
            }

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateBackend", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Backend>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Backend) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Backend)));
        }

        /// <summary>
        /// Create a new context 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>Context</returns>
        public Context CreateContext (Context context)
        {
             ApiResponse<Context> localVarResponse = CreateContextWithHttpInfo(context);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new context 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>ApiResponse of Context</returns>
        public ApiResponse< Context > CreateContextWithHttpInfo (Context context)
        {
            // verify the required parameter 'context' is set
            if (context == null)
                throw new ApiException(400, "Missing required parameter 'context' when calling ContextApi->CreateContext");

            var localVarPath = "/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (context != null && context.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(context); // http body (model) parameter
            }
            else
            {
                localVarPostBody = context; // byte array
            }

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateContext", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Context>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Context) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Context)));
        }

        /// <summary>
        /// Create a new context 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>Task of Context</returns>
        public async System.Threading.Tasks.Task<Context> CreateContextAsync (Context context)
        {
             ApiResponse<Context> localVarResponse = await CreateContextAsyncWithHttpInfo(context);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create a new context 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>Task of ApiResponse (Context)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Context>> CreateContextAsyncWithHttpInfo (Context context)
        {
            // verify the required parameter 'context' is set
            if (context == null)
                throw new ApiException(400, "Missing required parameter 'context' when calling ContextApi->CreateContext");

            var localVarPath = "/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (context != null && context.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(context); // http body (model) parameter
            }
            else
            {
                localVarPostBody = context; // byte array
            }

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateContext", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Context>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Context) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Context)));
        }

        /// <summary>
        /// Delete backend by id (not by ledgername) 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <returns></returns>
        public void DeleteBackend (string backendId)
        {
             DeleteBackendWithHttpInfo(backendId);
        }

        /// <summary>
        /// Delete backend by id (not by ledgername) 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteBackendWithHttpInfo (string backendId)
        {
            // verify the required parameter 'backendId' is set
            if (backendId == null)
                throw new ApiException(400, "Missing required parameter 'backendId' when calling ContextApi->DeleteBackend");

            var localVarPath = "/backends/{backendId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (backendId != null) localVarPathParams.Add("backendId", Configuration.ApiClient.ParameterToString(backendId)); // path parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteBackend", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Delete backend by id (not by ledgername) 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteBackendAsync (string backendId)
        {
             await DeleteBackendAsyncWithHttpInfo(backendId);

        }

        /// <summary>
        /// Delete backend by id (not by ledgername) 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteBackendAsyncWithHttpInfo (string backendId)
        {
            // verify the required parameter 'backendId' is set
            if (backendId == null)
                throw new ApiException(400, "Missing required parameter 'backendId' when calling ContextApi->DeleteBackend");

            var localVarPath = "/backends/{backendId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (backendId != null) localVarPathParams.Add("backendId", Configuration.ApiClient.ParameterToString(backendId)); // path parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteBackend", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Find existing backend(s) by id (single result) and/or ledgername (multiple results). Optionally including public backends of others 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>List&lt;Backend&gt;</returns>
        public List<Backend> FindBackends (string backendId, bool? includePublic = null)
        {
             ApiResponse<List<Backend>> localVarResponse = FindBackendsWithHttpInfo(backendId, includePublic);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Find existing backend(s) by id (single result) and/or ledgername (multiple results). Optionally including public backends of others 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>ApiResponse of List&lt;Backend&gt;</returns>
        public ApiResponse< List<Backend> > FindBackendsWithHttpInfo (string backendId, bool? includePublic = null)
        {
            // verify the required parameter 'backendId' is set
            if (backendId == null)
                throw new ApiException(400, "Missing required parameter 'backendId' when calling ContextApi->FindBackends");

            var localVarPath = "/backends/{backendId}/find";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (backendId != null) localVarPathParams.Add("backendId", Configuration.ApiClient.ParameterToString(backendId)); // path parameter
            if (includePublic != null) localVarQueryParams.Add("includePublic", Configuration.ApiClient.ParameterToString(includePublic)); // query parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FindBackends", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Backend>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Backend>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Backend>)));
        }

        /// <summary>
        /// Find existing backend(s) by id (single result) and/or ledgername (multiple results). Optionally including public backends of others 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>Task of List&lt;Backend&gt;</returns>
        public async System.Threading.Tasks.Task<List<Backend>> FindBackendsAsync (string backendId, bool? includePublic = null)
        {
             ApiResponse<List<Backend>> localVarResponse = await FindBackendsAsyncWithHttpInfo(backendId, includePublic);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Find existing backend(s) by id (single result) and/or ledgername (multiple results). Optionally including public backends of others 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>Task of ApiResponse (List&lt;Backend&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Backend>>> FindBackendsAsyncWithHttpInfo (string backendId, bool? includePublic = null)
        {
            // verify the required parameter 'backendId' is set
            if (backendId == null)
                throw new ApiException(400, "Missing required parameter 'backendId' when calling ContextApi->FindBackends");

            var localVarPath = "/backends/{backendId}/find";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (backendId != null) localVarPathParams.Add("backendId", Configuration.ApiClient.ParameterToString(backendId)); // path parameter
            if (includePublic != null) localVarQueryParams.Add("includePublic", Configuration.ApiClient.ParameterToString(includePublic)); // query parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FindBackends", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Backend>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Backend>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Backend>)));
        }

        /// <summary>
        /// Get existing backend by id (not by ledgername). Optionally including public backend of others 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>Backend</returns>
        public Backend GetBackend (string backendId, bool? includePublic = null)
        {
             ApiResponse<Backend> localVarResponse = GetBackendWithHttpInfo(backendId, includePublic);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get existing backend by id (not by ledgername). Optionally including public backend of others 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>ApiResponse of Backend</returns>
        public ApiResponse< Backend > GetBackendWithHttpInfo (string backendId, bool? includePublic = null)
        {
            // verify the required parameter 'backendId' is set
            if (backendId == null)
                throw new ApiException(400, "Missing required parameter 'backendId' when calling ContextApi->GetBackend");

            var localVarPath = "/backends/{backendId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (backendId != null) localVarPathParams.Add("backendId", Configuration.ApiClient.ParameterToString(backendId)); // path parameter
            if (includePublic != null) localVarQueryParams.Add("includePublic", Configuration.ApiClient.ParameterToString(includePublic)); // query parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetBackend", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Backend>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Backend) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Backend)));
        }

        /// <summary>
        /// Get existing backend by id (not by ledgername). Optionally including public backend of others 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>Task of Backend</returns>
        public async System.Threading.Tasks.Task<Backend> GetBackendAsync (string backendId, bool? includePublic = null)
        {
             ApiResponse<Backend> localVarResponse = await GetBackendAsyncWithHttpInfo(backendId, includePublic);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get existing backend by id (not by ledgername). Optionally including public backend of others 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="backendId">backendId</param>
        /// <param name="includePublic">includePublic (optional, default to false)</param>
        /// <returns>Task of ApiResponse (Backend)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Backend>> GetBackendAsyncWithHttpInfo (string backendId, bool? includePublic = null)
        {
            // verify the required parameter 'backendId' is set
            if (backendId == null)
                throw new ApiException(400, "Missing required parameter 'backendId' when calling ContextApi->GetBackend");

            var localVarPath = "/backends/{backendId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (backendId != null) localVarPathParams.Add("backendId", Configuration.ApiClient.ParameterToString(backendId)); // path parameter
            if (includePublic != null) localVarQueryParams.Add("includePublic", Configuration.ApiClient.ParameterToString(includePublic)); // query parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetBackend", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Backend>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Backend) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Backend)));
        }

        /// <summary>
        /// Get an existing context 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>Context</returns>
        public Context GetContext (string context)
        {
             ApiResponse<Context> localVarResponse = GetContextWithHttpInfo(context);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get an existing context 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>ApiResponse of Context</returns>
        public ApiResponse< Context > GetContextWithHttpInfo (string context)
        {
            // verify the required parameter 'context' is set
            if (context == null)
                throw new ApiException(400, "Missing required parameter 'context' when calling ContextApi->GetContext");

            var localVarPath = "/{context}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (context != null) localVarPathParams.Add("context", Configuration.ApiClient.ParameterToString(context)); // path parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetContext", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Context>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Context) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Context)));
        }

        /// <summary>
        /// Get an existing context 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>Task of Context</returns>
        public async System.Threading.Tasks.Task<Context> GetContextAsync (string context)
        {
             ApiResponse<Context> localVarResponse = await GetContextAsyncWithHttpInfo(context);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get an existing context 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">context</param>
        /// <returns>Task of ApiResponse (Context)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Context>> GetContextAsyncWithHttpInfo (string context)
        {
            // verify the required parameter 'context' is set
            if (context == null)
                throw new ApiException(400, "Missing required parameter 'context' when calling ContextApi->GetContext");

            var localVarPath = "/{context}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (context != null) localVarPathParams.Add("context", Configuration.ApiClient.ParameterToString(context)); // path parameter

            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetContext", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Context>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Context) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Context)));
        }

        /// <summary>
        /// List existing backends. 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;Backend&gt;</returns>
        public List<Backend> ListBackends ()
        {
             ApiResponse<List<Backend>> localVarResponse = ListBackendsWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// List existing backends. 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;Backend&gt;</returns>
        public ApiResponse< List<Backend> > ListBackendsWithHttpInfo ()
        {

            var localVarPath = "/backends";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListBackends", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Backend>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Backend>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Backend>)));
        }

        /// <summary>
        /// List existing backends. 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;Backend&gt;</returns>
        public async System.Threading.Tasks.Task<List<Backend>> ListBackendsAsync ()
        {
             ApiResponse<List<Backend>> localVarResponse = await ListBackendsAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// List existing backends. 
        /// </summary>
        /// <exception cref="Sphereon.SDK.Blockchain.Easy.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;Backend&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Backend>>> ListBackendsAsyncWithHttpInfo ()
        {

            var localVarPath = "/backends";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (oauth2schema) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListBackends", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Backend>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Backend>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Backend>)));
        }

    }
}
