/**
 * Easy Blockchain API
 * <b>The Easy Blockchain API is an easy to use API to store entries within chains. Currently it stores entries using the bitcoin blockchain by means of Factom or Multichain. The latter also allows for a private blockchain. In the future other solutions will be made available</b>    The flow is generally as follows:  1. Make sure a context is available using the / POST endpoint. Normally you only need one context. This is the place where backend providers and blockchain implementations are being specified.  2. Make sure a chain has been created using the /chain POST endpoint. Normally you only need one or a handful of chains. This is a relative expensive operation.  3. Store entries on the chain from step 2. The entries will contain the content and metadata you want to store forever on the specified chain.  4. Retrieve an existing entry from the chain to verify or retrieve data      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.10
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKBlockchainEasy/ApiClient', 'SphereonSDKBlockchainEasy/model/CommittedEntry'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CommittedEntry'));
  } else {
    // Browser globals (root is window)
    if (!root.EasyBlockchainApi) {
      root.EasyBlockchainApi = {};
    }
    root.EasyBlockchainApi.AnchoredEntryResponse = factory(root.EasyBlockchainApi.ApiClient, root.EasyBlockchainApi.CommittedEntry);
  }
}(this, function(ApiClient, CommittedEntry) {
  'use strict';




  /**
   * The AnchoredEntryResponse model module.
   * @module SphereonSDKBlockchainEasy/model/AnchoredEntryResponse
   * @version 0.10
   */

  /**
   * Constructs a new <code>AnchoredEntryResponse</code>.
   * Anchored Entry response
   * @alias module:SphereonSDKBlockchainEasy/model/AnchoredEntryResponse
   * @class
   * @param anchoredEntry {module:SphereonSDKBlockchainEasy/model/CommittedEntry} 
   * @param anchorState {module:SphereonSDKBlockchainEasy/model/AnchoredEntryResponse.AnchorStateEnum} 
   */
  var exports = function(anchoredEntry, anchorState) {
    var _this = this;

    _this['anchoredEntry'] = anchoredEntry;


    _this['anchorState'] = anchorState;


  };

  /**
   * Constructs a <code>AnchoredEntryResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:SphereonSDKBlockchainEasy/model/AnchoredEntryResponse} obj Optional instance to populate.
   * @return {module:SphereonSDKBlockchainEasy/model/AnchoredEntryResponse} The populated <code>AnchoredEntryResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('anchoredEntry')) {
        obj['anchoredEntry'] = CommittedEntry.constructFromObject(data['anchoredEntry']);
      }
      if (data.hasOwnProperty('anchorTimes')) {
        obj['anchorTimes'] = ApiClient.convertToType(data['anchorTimes'], ['Date']);
      }
      if (data.hasOwnProperty('currentAnchorTime')) {
        obj['currentAnchorTime'] = ApiClient.convertToType(data['currentAnchorTime'], 'Date');
      }
      if (data.hasOwnProperty('anchorState')) {
        obj['anchorState'] = ApiClient.convertToType(data['anchorState'], 'String');
      }
      if (data.hasOwnProperty('lastAnchorTime')) {
        obj['lastAnchorTime'] = ApiClient.convertToType(data['lastAnchorTime'], 'Date');
      }
      if (data.hasOwnProperty('firstAnchorTime')) {
        obj['firstAnchorTime'] = ApiClient.convertToType(data['firstAnchorTime'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {module:SphereonSDKBlockchainEasy/model/CommittedEntry} anchoredEntry
   */
  exports.prototype['anchoredEntry'] = undefined;
  /**
   * All the times at which the Entry with the same Id was anchored in the blockchain in ISO 8601 format. The first, current and last Anchor Times will also be in this list
   * @member {Array.<Date>} anchorTimes
   */
  exports.prototype['anchorTimes'] = undefined;
  /**
   * The current anchor time (this is not necessarely the last anchor time!) of the entry (if any) in the blockchain in ISO 8601 format
   * @member {Date} currentAnchorTime
   */
  exports.prototype['currentAnchorTime'] = undefined;
  /**
   * @member {module:SphereonSDKBlockchainEasy/model/AnchoredEntryResponse.AnchorStateEnum} anchorState
   */
  exports.prototype['anchorState'] = undefined;
  /**
   * The last anchor time of the entry (if any) in the blockchain in ISO 8601 format
   * @member {Date} lastAnchorTime
   */
  exports.prototype['lastAnchorTime'] = undefined;
  /**
   * The first anchor time of the entry (if any) in the blockchain in ISO 8601 format
   * @member {Date} firstAnchorTime
   */
  exports.prototype['firstAnchorTime'] = undefined;


  /**
   * Allowed values for the <code>anchorState</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AnchorStateEnum = {
    /**
     * value: "REQUESTED"
     * @const
     */
    "REQUESTED": "REQUESTED",
    /**
     * value: "COMMITTED"
     * @const
     */
    "COMMITTED": "COMMITTED",
    /**
     * value: "NOT_FOUND"
     * @const
     */
    "NOT_FOUND": "NOT_FOUND",
    /**
     * value: "ANCHORED"
     * @const
     */
    "ANCHORED": "ANCHORED"  };


  return exports;
}));


