<?php
/**
 * EntryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Sphereon\SDK\Blockchain\Easy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Easy Blockchain API
 *
 * The Easy Blockchain API is an easy to use API to store related entries within chains. Currently it stores entries using a Factom, Ethereum or Multichain blockchain.   For full API documentation please visit: https://docs.sphereon.com/api/easy-blockchain/0.10/html   Interactive testing: A web based test console is available in the Sphereon API store at: https://store.sphereon.com
 *
 * OpenAPI spec version: 0.10
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Sphereon\SDK\Blockchain\Easy;

use \Sphereon\SDK\Blockchain\Easy\Configuration;
use \Sphereon\SDK\Blockchain\Easy\ApiClient;
use \Sphereon\SDK\Blockchain\Easy\ApiException;
use \Sphereon\SDK\Blockchain\Easy\ObjectSerializer;

/**
 * EntryApiTest Class Doc Comment
 *
 * @category Class
 * @package  Sphereon\SDK\Blockchain\Easy
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EntryApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createEntry
     *
     * Create a new entry in the provided chain.
     *
     */
    public function testCreateEntry()
    {
    }

    /**
     * Test case for entryById
     *
     * Get an existing entry in the provided chain.
     *
     */
    public function testEntryById()
    {
    }

    /**
     * Test case for entryByRequest
     *
     * Get an existing entry in the provided chain.
     *
     */
    public function testEntryByRequest()
    {
    }

    /**
     * Test case for firstEntry
     *
     * Get the first entry in the provided chain.
     *
     */
    public function testFirstEntry()
    {
    }

    /**
     * Test case for lastEntry
     *
     * Get the last entry in the provided chain..
     *
     */
    public function testLastEntry()
    {
    }

    /**
     * Test case for nextEntryById
     *
     * Get the entry after the supplied entry Id (the next) in the provided chain.
     *
     */
    public function testNextEntryById()
    {
    }

    /**
     * Test case for nextEntryByRequest
     *
     * Get the entry after the supplied entry Id (the next) in the provided chain.
     *
     */
    public function testNextEntryByRequest()
    {
    }

    /**
     * Test case for previousEntryById
     *
     * Get the entry before the supplied entry Id (the previous) in the provided chain.
     *
     */
    public function testPreviousEntryById()
    {
    }

    /**
     * Test case for previousEntryByRequest
     *
     * Get the entry before the supplied entry Id (the previous) in the provided chain.
     *
     */
    public function testPreviousEntryByRequest()
    {
    }
}
