<?php
/**
 * AnchoredEntryResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Easy Blockchain API
 *
 * The Easy Blockchain API is an easy to use API to store related entries within chains. Currently it stores entries using a Factom, Ethereum or Multichain blockchain.   For full API documentation please visit: https://docs.sphereon.com/api/easy-blockchain/0.10/html   Interactive testing: A web based test console is available in the Sphereon API store at: https://store.sphereon.com
 *
 * OpenAPI spec version: 0.10
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AnchoredEntryResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Anchored Entry response
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AnchoredEntryResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AnchoredEntryResponse"
     */
    public function testAnchoredEntryResponse()
    {
    }

    /**
     * Test attribute "anchored_entry"
     */
    public function testPropertyAnchoredEntry()
    {
    }

    /**
     * Test attribute "anchor_times"
     */
    public function testPropertyAnchorTimes()
    {
    }

    /**
     * Test attribute "current_anchor_time"
     */
    public function testPropertyCurrentAnchorTime()
    {
    }

    /**
     * Test attribute "anchor_state"
     */
    public function testPropertyAnchorState()
    {
    }

    /**
     * Test attribute "last_anchor_time"
     */
    public function testPropertyLastAnchorTime()
    {
    }

    /**
     * Test attribute "first_anchor_time"
     */
    public function testPropertyFirstAnchorTime()
    {
    }
}
