//
// Access.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Access: Codable {

    public enum Modes: String, Codable { 
        case _none = "NONE"
        case read = "READ"
        case write = "WRITE"
        case _public = "PUBLIC"
    }
    public var modes: [Modes]?
    public var blackList: [String]?
    public var whiteList: [String]?

    public init() {}

}
