//
// ModelError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An error */
open class ModelError: Codable {

    public enum Level: String, Codable { 
        case info = "INFO"
        case warning = "WARNING"
        case fatal = "FATAL"
    }
    public var code: String?
    public var level: Level?
    public var cause: ModelError?
    public var message: String?

    public init() {}

}
