//
// ModelErrorResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The error response */
open class ModelErrorResponse: Codable {

    public var errors: [ModelError]?

    public init() {}

}
